#!/bin/sh
# Setup script to define the location of this library and the output folders
# to allow this library to be used in other builds

set -a

# Define the location of this library
SPINN_COMMON_DIRS=$PWD

# Define the location of the headers
SPINN_COMMON_INCLUDE=$SPINN_COMMON_DIRS/include

# Define the location of the library
SPINN_COMMON_LIBS=$SPINN_COMMON_DIRS/lib

# Define the location of the build
SPINN_COMMON_BUILD=$SPINN_COMMON_DIRS/build
